### ISSUE TITLE
Animation Preview is serializing transforms to my Character

### ISSUE THREAD

**Issue by rgvox** [Baste-RainGames/AnimationPlayer#8] opened 2018-03-21 23:52 UTC
I like that I can preview the animations in the inspector window, but it has some fun consequences.  My character is sitting in my scene half way through an animation, stuck that way.  It doesn't cause any animation problems on startup, but i'm using PuppetMaster which requires my ragdoll to match up with my rig on app startup.  I'm still looking into how to rectify this problem.  I may have to use my old rig's transform and do some sort of retargeting between the good one (t-pose) and the borked one and then serialize those positions/rotations back to my scene.  Not quite sure yet how I'll fix it.

**Comment by Baste-RainGames** [comment] 2018-03-22 10:11
I know, it's horrible.

You can get the rig back into the bind pose by optimizing and then deoptimizing the transform hierarchy. You do that from the cog-menu on an animator. That's not an ideal situation, but it might help you right now.

I'm not quite sure how I convince the animation playback to go back to the default pose. I might save the transform position of each bone and revert that after preview, but that doesn't work on optimized characters and will cause previews to dirty the scene.

Any ideas? I'd really like to figure out a way to handle animation previews properly. It might be that I can play them in a different way.

**Comment by Baste-RainGames** [comment] 2018-03-22 16:29
Fixed it!

AnimationStatePreviewer.Cleanup got a bit funky:

```cs
public void Cleanup()
{
    if (previewGraph.IsValid())
        previewGraph.Destroy();
    
    //Reset the object to the bind pose. Only way I've found is to play an empty clip for a single frame.
    var resetGraph = PlayableGraph.Create();
    var animator = animationPlayer.gameObject.EnsureComponent<Animator>();
    var animOutput = AnimationPlayableOutput.Create(resetGraph, "Cleanup Graph", animator);
    animOutput.SetSourcePlayable(AnimationClipPlayable.Create(resetGraph, new AnimationClip()));
    resetGraph.SetTimeUpdateMode(DirectorUpdateMode.Manual);
    resetGraph.GetRootPlayable(0).SetTime(0);
    resetGraph.Evaluate();
    resetGraph.Destroy();
}
```

I happened to have a state without a clip on it, and noticed that playing it set the character to the bind pose, so that made it pretty straight-forward to figure out.

Could you check that this works for you, @rgvox? If it does, I'll close the issue.

**Comment by rgvox** [comment] 2018-03-23 03:33
This does to appear to sort out the original issue.  I wasn't able to get my character back to its original pose yet though.  I can confirm that the pose that I'm in before the preview is the pose that I end up in after I stop the preview :)

**Comment by rgvox** [comment] 2018-03-23 05:09
I figured out how to do it!  I sort of looped over all the transforms in my borked one, and had them all match the respective transform of the one that's good.  I did notice something weird with the above code.  When I used Unity's "play" button to test my scene, and then stopped the debug, it errored because my animationPlayer seemed to be null for some reason.  I wonder if it that was just something weird or not, but anyways all of my errors are now fixed here :)

**Comment by rgvox** [comment] 2018-03-23 06:24
Hrm, so I removed my custom code and then the new code you added somehow put it back to the bad pose.  I think it did so because the animator still had something stored about the prior borked pose.  Anyways, I took the new code out for now, but I'm curious how to get my animationplayer instance back to a clean state so I can start using the preview again :)

**Comment by Baste-RainGames** [comment] 2018-03-31 16:45
Well would you look at that, I found out what the issue is.

The fix I introduced (playing an empty animation) only works for _optimized transform hierarchies_. This means that you either turn "Optimize Game Objects" on in the .fbx/.blend file's Rig tab, hit "Optimize Transform Hierarchy" in the Animator's cog menu, or call AnimatorUtility.OptimizeTransformHierarchy on it.

I'll have to try to find a solution that works even in unoptimized settings. Since I can't detect if the hierarchy is optimized (API for that is missing), and optimizing the hierarchy breaks prefab connections _and_ there's the issue of exposed transforms, I can't implement a solution around optimizing and then maybe deoptimizing.

That being said, I really recommend always optimizing the hierarchy unless you need bones exposed. That's usually only the case either if you need to attach objects to part of the model, or if you're doing IK outside the humanoid system. Optimized rigs are much faster.

**Closed as completed** 2019-08-06 14:36 UTC
